//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace firstProject.satinder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="lengthUnitSoap", Namespace="http://www.webserviceX.NET/")]
    public partial class lengthUnit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeLengthUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public lengthUnit() {
            this.Url = global::firstProject.Properties.Settings.Default.firstProject_satinder_lengthUnit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeLengthUnitCompletedEventHandler ChangeLengthUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ChangeLengthUnit", RequestNamespace="http://www.webserviceX.NET/", ResponseNamespace="http://www.webserviceX.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ChangeLengthUnit(double LengthValue, Lengths fromLengthUnit, Lengths toLengthUnit) {
            object[] results = this.Invoke("ChangeLengthUnit", new object[] {
                        LengthValue,
                        fromLengthUnit,
                        toLengthUnit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeLengthUnitAsync(double LengthValue, Lengths fromLengthUnit, Lengths toLengthUnit) {
            this.ChangeLengthUnitAsync(LengthValue, fromLengthUnit, toLengthUnit, null);
        }
        
        /// <remarks/>
        public void ChangeLengthUnitAsync(double LengthValue, Lengths fromLengthUnit, Lengths toLengthUnit, object userState) {
            if ((this.ChangeLengthUnitOperationCompleted == null)) {
                this.ChangeLengthUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeLengthUnitOperationCompleted);
            }
            this.InvokeAsync("ChangeLengthUnit", new object[] {
                        LengthValue,
                        fromLengthUnit,
                        toLengthUnit}, this.ChangeLengthUnitOperationCompleted, userState);
        }
        
        private void OnChangeLengthUnitOperationCompleted(object arg) {
            if ((this.ChangeLengthUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeLengthUnitCompleted(this, new ChangeLengthUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Lengths {
        
        /// <remarks/>
        Angstroms,
        
        /// <remarks/>
        Nanometers,
        
        /// <remarks/>
        Microinch,
        
        /// <remarks/>
        Microns,
        
        /// <remarks/>
        Mils,
        
        /// <remarks/>
        Millimeters,
        
        /// <remarks/>
        Centimeters,
        
        /// <remarks/>
        Inches,
        
        /// <remarks/>
        Links,
        
        /// <remarks/>
        Spans,
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Cubits,
        
        /// <remarks/>
        Varas,
        
        /// <remarks/>
        Yards,
        
        /// <remarks/>
        Meters,
        
        /// <remarks/>
        Fathoms,
        
        /// <remarks/>
        Rods,
        
        /// <remarks/>
        Chains,
        
        /// <remarks/>
        Furlongs,
        
        /// <remarks/>
        Cablelengths,
        
        /// <remarks/>
        Kilometers,
        
        /// <remarks/>
        Miles,
        
        /// <remarks/>
        Nauticalmile,
        
        /// <remarks/>
        League,
        
        /// <remarks/>
        Nauticalleague,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ChangeLengthUnitCompletedEventHandler(object sender, ChangeLengthUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeLengthUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeLengthUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591